<h1>Cours 5 : Régression, Cross-Validation, Pénalisation (TP 9-10)<span class="tocSkip"></span></h1>

Dans ce cours, nous présenterons la régression linéaire sous son aspect bayésien et ses extensions. <br>

La première partie traite de la régression linéaire sous son approche habituelle, vous entraîne à l'implémenter, vous initie à la validation de modèle et propose des exercices pour vous entraîner.<br>

La seconde partie traite des différentes pénalisations de la régression linéaire. Les extensions du type LASSO et RIDGE seront explorées. <br>


<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Modèle-linéaire" data-toc-modified-id="Modèle-linéaire-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Modèle linéaire</a></span><ul class="toc-item"><li><span><a href="#Exercice" data-toc-modified-id="Exercice-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Exercice</a></span></li></ul></li><li><span><a href="#Validation" data-toc-modified-id="Validation-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Validation</a></span><ul class="toc-item"><li><span><a href="#Exercice" data-toc-modified-id="Exercice-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Exercice</a></span></li></ul></li><li><span><a href="#Pénalisation" data-toc-modified-id="Pénalisation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Pénalisation</a></span><ul class="toc-item"><li><span><a href="#Ridge" data-toc-modified-id="Ridge-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Ridge</a></span></li><li><span><a href="#Lasso" data-toc-modified-id="Lasso-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Lasso</a></span></li></ul></li></ul></div>

## Modèle linéaire

Le modèle générateur est de la forme $Y_t = X_t \theta + \varepsilon$ <br>
$\varepsilon_t$ iid $\sim \mathcal{N}(0,\sigma^2)$ <br>
On recherche le paramètre $\theta$ sur notre jeu de données en minimisant la fonction de perte :<br>

\begin{equation*}
 L(\theta) = || Y - X\theta||^2_2
\end{equation*}

Après quelques calculs (dérivée = 0), on trouve que :
\begin{equation*}
\hat{\theta} = (X^TX)^{-1}X^TY
\end{equation*}



### Exercice

1) Implémenter une fonction compute_estimator() qui calcule l'estimateur d'un modèle linéaire en prenant en entrée X et Y.

In [1]:
import pandas as pd
import numpy as np

np.random.seed(2)
theta_0 = 3
theta_1 = 0.5
X = np.linspace(1, 100, num = 50)
epsilon = np.random.normal(0,1, size=50)

Y=theta_0 + theta_1*X+epsilon

In [2]:
def compute_estimator(X,Y):
    X = X.reshape(len(X),1)
    tmp = np.ones(shape=(len(X),1))
    print(X.shape)
    print(tmp.shape)
    X= np.concatenate((tmp,X),axis=1)
    Y = Y.reshape(len(Y),1)
    
    ##Votre code
    t1 = np.linalg.inv(np.dot(np.transpose(X),X))
    t2 = np.dot(np.transpose(X),Y)
    return np.dot(t1,t2)

In [3]:
compute_estimator(X,Y)

(50, 1)
(50, 1)


array([[2.54979832],
       [0.50614768]])

FLORIE +1, LEA +1

2) En utilisant l'estimateur calculé, prédire Y_prime en utilisant X_prime

In [4]:
np.random.seed(2)
X_prime = np.random.uniform(low=0, high=10, size=(100,))
def prediction(X_prime,theta):
    ##Votre code
    Y_prime = theta[0]+X_prime*theta[1]
    return Y_prime

In [5]:
prediction(X_prime,compute_estimator(X,Y))

(50, 1)
(50, 1)


array([4.75657639, 2.68102334, 5.33190219, 4.7531725 , 4.67748019,
       4.22178034, 3.58562263, 5.68422393, 4.06649349, 3.90033838,
       5.69365279, 5.22803874, 3.23097159, 5.14926205, 3.48333642,
       6.52475393, 6.87217443, 5.05136659, 6.83464962, 2.95292205,
       5.10708967, 2.88024445, 4.71672954, 3.03838731, 3.19341556,
       5.57021084, 3.69375281, 3.09110142, 3.66487307, 4.32043594,
       4.91749381, 3.57091697, 5.79120209, 4.99484507, 5.10704224,
       4.50804649, 6.56677586, 5.485476  , 3.37126891, 6.09664005,
       7.43185121, 5.08057903, 7.05208346, 4.27886789, 5.42038515,
       4.71381228, 4.76038445, 6.4803346 , 5.2607464 , 7.37714245,
       5.30429528, 2.96531986, 4.40403188, 6.85635838, 4.60615001,
       2.68748246, 3.80088017, 2.88964799, 7.58015719, 7.46236803,
       6.60028738, 5.5958817 , 6.42162489, 3.40632899, 4.0329286 ,
       5.20235064, 4.35484384, 2.78100134, 7.52600665, 4.78370599,
       5.10078484, 4.18739518, 3.86449035, 4.50803249, 6.76103

3) Comparer vos résultats en utilisant LinearRegression de scikit-learn.

In [6]:
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [7]:
lr = LinearRegression()
lr.fit(X.reshape(len(X),1),Y)
lr.predict(X_prime.reshape(len(X_prime),1))

/Users/LF/anaconda/lib/python3.6/site-packages/sklearn/linear_model/base.py:509: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  linalg.lstsq(X, y)


array([4.75657639, 2.68102334, 5.33190219, 4.7531725 , 4.67748019,
       4.22178034, 3.58562263, 5.68422393, 4.06649349, 3.90033838,
       5.69365279, 5.22803874, 3.23097159, 5.14926205, 3.48333642,
       6.52475393, 6.87217443, 5.05136659, 6.83464962, 2.95292205,
       5.10708967, 2.88024445, 4.71672954, 3.03838731, 3.19341556,
       5.57021084, 3.69375281, 3.09110142, 3.66487307, 4.32043594,
       4.91749381, 3.57091697, 5.79120209, 4.99484507, 5.10704224,
       4.50804649, 6.56677586, 5.485476  , 3.37126891, 6.09664005,
       7.43185121, 5.08057903, 7.05208346, 4.27886789, 5.42038515,
       4.71381228, 4.76038445, 6.4803346 , 5.2607464 , 7.37714245,
       5.30429528, 2.96531986, 4.40403188, 6.85635838, 4.60615001,
       2.68748246, 3.80088017, 2.88964799, 7.58015719, 7.46236803,
       6.60028738, 5.5958817 , 6.42162489, 3.40632899, 4.0329286 ,
       5.20235064, 4.35484384, 2.78100134, 7.52600665, 4.78370599,
       5.10078484, 4.18739518, 3.86449035, 4.50803249, 6.76103

4) Charger la table cours_5_data.csv. Prenez X = "Item_Stock" et Y = "Item_Outlet_Sales", calculer l'estimateur $\theta$.

In [8]:
df=pd.read_csv("../data/cours_5_data.csv")

In [11]:
X = df["Item_Stock"]
y = df["Item_Outlet_Sales"]

In [13]:
compute_estimator(X.values,y.values)

(7060, 1)
(7060, 1)


array([[-36.26504787],
       [ 15.25687788]])

In [19]:
X.values

array([249.8092,  48.2692, 141.618 , ...,  85.1224, 103.1332,  75.467 ])

In [20]:
lr = LinearRegression()
lr.fit(X.values.reshape(X.shape[0],1),y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [24]:
print("coef : "+str(lr.coef_))
print("intercept : "+str(lr.intercept_))

coef : [15.25687788]
intercept : -36.26504786675196


## Validation

Dans la majorité des cas, nous sommes confrontés à des problèmes de prédiction où il y a une base d'entraînement et une base de test pour pouvoir mesurer et "valider" la qualité de notre prédiction. Cette bonne pratique permet d'éviter un overfitting sur l'échantillon d'apprentissage, en vérifiant le score sur l'échantillon test, les deux doivent être similaires.

### Exercice

1) Trouver une fonction dans scikit-learn qui sépare en 2 échantillons la table cours_5_data.csv, séparez cette table en 67% apprentissage et 33% test. Utilisez 2 comme seed. <br>
2) Construire une fonction erreur_quadratique_moyenne() pour mesurer l'erreur sur la base test entre vos prédictions et la valeur réelle de Y. Faites de même en prédisant le Y de la base d'apprentissage et regardez l'erreur quadratique moyenne. Qu'en déduisez-vous ?

In [26]:
from sklearn.model_selection import train_test_split

In [70]:
df.head()

Item_Weight  Item_Visibility  Item_Stock  Outlet_Establishment_Year  \
0         9.30         0.016047    249.8092                       1999   
1         5.92         0.019278     48.2692                       2009   
2        17.50         0.016760    141.6180                       1999   
3        19.20         0.000000    182.0950                       1998   
4         8.93         0.000000     53.8614                       1987   

   Item_Outlet_Sales  
0          3735.1380  
1           443.4228  
2          2097.2700  
3           732.3800  
4           994.7052

In [93]:
X = df[["Item_Stock","Item_Weight","Item_Visibility"]]
y = df["Item_Outlet_Sales"]

In [94]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=2)

In [95]:
X_train.shape,X_test.shape

((4730, 3), (2330, 3))

In [96]:
def erreur_quadratique_moyenne(y_pred,y_true): #MSE
    return(np.mean(np.square(y_pred-y_true)))
def rac_erreur_quadratique_moyenne(y_pred,y_true): #RMSE
    return (np.sqrt(np.mean(np.square(y_pred-y_true))))
def erreur_absolue_moyenne(y_pred,y_true): #MAE
    return (np.mean(np.abs(y_pred-y_true)))

In [97]:
lr=LinearRegression()
lr.fit(X_train.values.reshape(X_train.shape[0],3),y_train)
y_pred=lr.predict(X_test.values.reshape(X_test.shape[0],3))
y_pred_train=lr.predict(X_train.values.reshape(X_train.shape[0],3))

In [98]:
eam_test=erreur_absolue_moyenne(y_pred,y_test)
raqm_test=rac_erreur_quadratique_moyenne(y_pred,y_test)

In [99]:
raqm_train=rac_erreur_quadratique_moyenne(y_pred_train,y_train)
eam_train=erreur_absolue_moyenne(y_pred_train,y_train)

In [100]:
print("MAE test : {}, RMSE test : {}, MAE train : {}, RMSE train {}".format(eam_test,raqm_test,raqm_train,eam_train))

MAE test : 868.5290638051998, RMSE test : 1177.7954799869544, MAE train : 1204.1761486416638, RMSE train 890.6697431565144


In [92]:
print("MAE test : {}, RMSE test : {}, MAE train : {}, RMSE train {}".format(eam_test,raqm_test,raqm_train,eam_train))

MAE test : 872.2943867353413, RMSE test : 1184.7665887590717, MAE train : 1210.5447621332578, RMSE train 890.0802803874024


In [72]:
print("MAE test : {}, RMSE test : {}, MAE train : {}, RMSE train {}".format(eam_test,raqm_test,raqm_train,eam_train))

MAE test : 871.3421860903337, RMSE test : 1183.920033957123, MAE train : 1210.6721292543189, RMSE train 890.0865017575998


## Pénalisation

Les régressions pénalisés sont des techniques puissantes généralement utilisées pour créer des modèles parcimonieux en présence d'un "grand" nombre de variables :<br>

- Suffisamment grand pour accroître la tendance d'un modèle à l'overfitting. 
- Assez grand pour causer des problèmes de calcul (problème d'inversion de matrice). <br>

Nous allons présenter deux types de pénalisations appelées Ridge et Lasso. <br>
La principale différence réside dans la façon dont ils attribuent les pénalités aux coefficients. <br>


### Ridge

On pénalise la fonction de perte avec un terme supplémentaire qui contraint de façon quadratique le paramètre $\theta$: \begin{equation*}
 L(\theta,\lambda) = || Y - X\theta||^2_2 + \lambda ||\theta||^2_2
\end{equation*}

Trouver le paramètre $\hat{\theta}$ qui minimise la fonction de perte.
#explication ridge tableau

### Lasso

Le Lasso pénalise la fonction de perte en essayant de neutraliser au maximum l'accroissement absolu des variables : 

\begin{equation*}
 L(\theta,\lambda) = || Y - X\theta||^2_2 + \lambda ||\theta||^2_1
\end{equation*}
#explication tableau

Trouvez-les fonctions Ridge et Lasso dans scikit-learn, amusez-vous avec le jeu de données et comparer les erreurs de chaque méthode, à la fois sur l'échantillon d'apprentissage et l'échantillon de test. Par ailleurs, comparer aussi les coefficients estimés entre les 3 méthodes (regression simple, penalisation Ridge, penalisation Lasso).

In [258]:
from sklearn.datasets import load_boston 

In [278]:
y=load_boston()["target"]
X=load_boston()["data"]

In [279]:
X_1=X+np.random.normal(0,1)
X_2=X+np.random.normal(0,1)
X_3=X+np.random.normal(0,1)
X_4=X+np.random.normal(0,1)
X_5=X+np.random.normal(0,1)

In [280]:
X=np.concatenate([X_1,X_2,X_3,X_4,X_5],axis=1)

In [281]:
X=X[:60,:]
y=y[:60]

In [282]:
#X = df[["Item_Stock","Item_Weight","Item_Visibility","Outlet_Establishment_Year"]]
#y = df["Item_Outlet_Sales"]

In [283]:
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [284]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=2)

In [285]:
alphas = [0.000001,0.001,0.01,0.1,0.5,1,5,10,15,20,30,50,100,500,1000,2000,5000,10000]

In [286]:
alphas_2=np.linspace(0.7,1.4,20)

In [287]:
for alp in alphas_2:
    ridge=Ridge(alpha=alp)
    ridge.fit(X_train,y_train)
    y_pred=ridge.predict(X_train)
    print("alpha : "+str(alp)+" MAE : "+str(erreur_absolue_moyenne(y_pred,y_train)))

alpha : 0.7 MAE : 1.4416166707626146
alpha : 0.7368421052631579 MAE : 1.442478267196894
alpha : 0.7736842105263158 MAE : 1.4432796035819409
alpha : 0.8105263157894737 MAE : 1.44402826210578
alpha : 0.8473684210526315 MAE : 1.4447305564571213
alpha : 0.8842105263157894 MAE : 1.4453917875620939
alpha : 0.9210526315789473 MAE : 1.4460164398750626
alpha : 0.9578947368421051 MAE : 1.4466083336866615
alpha : 0.9947368421052631 MAE : 1.4471707445011117
alpha : 1.031578947368421 MAE : 1.44770649756904
alpha : 1.068421052631579 MAE : 1.448565759054484
alpha : 1.1052631578947367 MAE : 1.4494911329374247
alpha : 1.1421052631578945 MAE : 1.4503928133512651
alpha : 1.1789473684210525 MAE : 1.4512724896236482
alpha : 1.2157894736842105 MAE : 1.4521316595774996
alpha : 1.2526315789473683 MAE : 1.4529716568817121
alpha : 1.289473684210526 MAE : 1.4537936737924166
alpha : 1.3263157894736841 MAE : 1.4545987802094633
alpha : 1.3631578947368421 MAE : 1.4553879397109655
alpha : 1.4 MAE : 1.4561620230848848

In [288]:
for alp in alphas:
    lasso=Lasso(alpha=alp)
    lasso.fit(X_train,y_train)
    y_pred=lasso.predict(X_train)
    print("alpha : "+str(alp)+" MAE : "+str(erreur_absolue_moyenne(y_pred,y_train)))

alpha : 1e-06 MAE : 1.291254136678082
alpha : 0.001 MAE : 1.288830640869778
alpha : 0.01 MAE : 1.450108707061522
alpha : 0.1 MAE : 1.5450506285397971
alpha : 0.5 MAE : 2.017404050550995
alpha : 1 MAE : 2.2871676679738533
alpha : 5 MAE : 2.7600904494669525
alpha : 10 MAE : 2.935666807003961
alpha : 15 MAE : 3.0594186892609274
alpha : 20 MAE : 3.1427673071434326
alpha : 30 MAE : 3.318095390541842
alpha : 50 MAE : 3.739507371523281
alpha : 100 MAE : 4.606056863027363
alpha : 500 MAE : 5.188
alpha : 1000 MAE : 5.188
alpha : 2000 MAE : 5.188
alpha : 5000 MAE : 5.188
alpha : 10000 MAE : 5.188


/Users/LF/anaconda/lib/python3.6/site-packages/sklearn/linear_model/coordinate_descent.py:491: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)


In [295]:
alpha_ridge = 0.1
alpha_lasso = 0.1

In [296]:
ridge=Ridge(alpha=alpha_ridge)
ridge.fit(X_train,y_train)
y_pred_ridge = ridge.predict(X_test)
lasso=Lasso(alpha=alpha_lasso)
lasso.fit(X_train,y_train)
y_pred_lasso = lasso.predict(X_test)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred_lr = lr.predict(X_test)

In [297]:
print("ridge "+str(erreur_absolue_moyenne(y_pred_ridge,y_test)))
print("lasso "+str(erreur_absolue_moyenne(y_pred_lasso,y_test)))
print("linear reg "+str(erreur_absolue_moyenne(y_pred_lr,y_test)))

ridge 2.8788922155716414
lasso 2.672195817951981
linear reg 2.732334098815918


In [250]:
print("linear reg "+str(erreur_absolue_moyenne(y_pred_lr,y_test)))

linear reg 1.620961680556789
